version: '3'

services:
  pythonAPI:
    build:
      context: ./api/Dockerfile
      image: PythonFlask_API
    networks:
      API-net:
        ipv4_address: 192.168.10.10
    ports:
      - 5000:5000 # Quitar Cuando este funcionando a traves de Cloudflare Tunnel Puerto expuesto en la imagen
    volumes:
      - api-data:/var/api
    restart: unless-stopped
    container_name: pythonAPI
    hostname: pythonAPI
    domainname: pythonAPI
    stdin_open: true 
    tty: true
  
  mongoServer:
    build:
      context: ./mongodb/Dockerfile
      image: MongoDB_Python_Cron
    environment:
      MONGO_INITDB_ROOT_USERNAME: carlos
      MONGO_INITDB_ROOT_PASSWORD: carlos
    volumes:
      - mongo-data:/data/db
    networks:
      API-net:
        ipv4_address: 192.168.10.20
    restart: unless-stopped
    container_name: mongoServer
    hostname: mongoServer
    domainname: mongoServer
    stdin_open: true 
    tty: true

  apacheServer:
    image: php:apache-bullseye
    expose:
      - 80
      - 443
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - web-data:/var/www/web
    networks:
      API-net:
        ipv4_address: 192.168.10.30
    container_name: apacheServer
    hostname: apacheServer
    domainname: apacheServer
    stdin_open: true 
    tty: true

volumes:
  mongo-data:
  api-data:
  web-data:

networks:
  API-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"