version: '3'

services:
  pythonAPI:
    build:
      context: ./api/Dockerfile
      image: PythonFlask_API
    networks:
      API-net:
      ipv4_address: 192.168.10.10
    ports:
      - 5000:5000 # Quitar Cuando este funcionando a traves de Cloudflare Tunnel Puerto expuesto en la imagen
    restart: unless-stopped
    container_name: pythonAPI
    hostname: pythonAPI
    domainname: pythonAPI
  
  mongoServer:
    build:
      context: ./mongodb/Dockerfile
      image: MongoDB_Python_Cron
    environment:
      MONGO_INITDB_ROOT_USERNAME: carlos
      MONGO_INITDB_ROOT_PASSWORD: carlos
    volumes:
      - mongo-data:/data/db
    networks:
      API-net:
        ipv4_address: 192.168.10.20
    restart: unless-stopped
    container_name: mongoServer
    hostname: mongoServer
    domainname: mongoServer

  apacheServer:
    image: php:apache-bullseye
    expose:
      - 80
      - 443
    restart: unless-stopped
    networks:
      API-net:
        ipv4_address: 192.168.10.30
    container_name: apacheServer
    hostname: apacheServer
    domainname: apacheServer
  
  cloudflaretunnel:
    image: cloudflare/cloudflare:latest
    restart: unless-stopped
    networks:
      API-net:
        ipv4_address: 192.168.10.40
    command: tunnel run --token <MY_TOKEN>

volumes:
  mongo-data:

networks:
  API-net:
    driver: bridge
    ipam:
      driver: default
      config:
        -subnet: "192.168.10.0/24"