version: '3'

services:
  pythonAPI:
    build:
      context: ./api/Dockerfile
      image: PythonFlask_API
    networks:
      API-net:
      ipv4_address: 192.168.10.10
    ports:
      - 5000:5000 # Quitar Cuando este funcionando a traves de Cloudflare Tunnel Puerto expuesto en la imagen
    restart: unless-stopped
    container_name: pythonAPI
    hostname: pythonAPI
    domainname: pythonAPI
  
  mongoServer:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: carlos
      MONGO_INITDB_ROOT_PASSWORD: example # Se tiene que cambiar. Nosé si dejarlo Hardcodeado
    volumes:
      - mongo-data:/data/db
    networks:
      API-net:
        ipv4_address: 192.168.10.20
    expose:
      - "27017"
    container_name: mongoServer
    hostname: mongoServer
    domainname: mongoServer
  # Añadir CloudFlare Tunnel

volumes:
  mongo-data:

networks:
  API-net:
    driver: bridge
    ipam:
      driver: default
      config:
        -subnet: "192.168.10.0/24"