version: '3'

services:
  api:
    build:
      context: .
      image: PythonFlask_API
    networks:
      - API-net
    ports:
      - 5000:5000 # Quitar cuando la aplicación esté trabajando en el proxy inverso
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: carlos
      MONGO_INITDB_ROOT_PASSWORD: example # Se tiene que cambiar
    volumes:
      - mongo-data:/data/db
    networks:
      - API-net

  # nginxProxyManager:
  #   ports:
  #     - 443:443


volumes:
  mongo-data:

networks:
  API-net:
    driver: bridge
    ipam:
      driver: default
      config:
        -subnet: "192.168.0.0/24"